spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/gulimall_pms?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#    alicloud:
#      access-key: LTAI5tSYPBDnUdptFoYqHrTb
#      secret-key: Kl5FGPeQiUx48ps8asomlEp4T9g57n
#      oss:
#        endpoint: oss-cn-chengdu.aliyuncs.com


  redis:
    host: 192.168.48.129
    port: 6379

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      #配置逻辑删除 删除的值为1，未删除的值为0
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10001
logging:
  level:
    com.atguigu.gulimall: debug
