spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tSYPBDnUdptFoYqHrTb
      secret-key: Kl5FGPeQiUx48ps8asomlEp4T9g57n
      oss:
        endpoint: oss-cn-chengdu.aliyuncs.com
        bucket: gulimall-hyq

  application:
    name: gulimall-third-party

server:
  port: 30000
